const data = [
  {
    id:1,
    name: "V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/vhotel.jpg",
    roomProperty:[
     {
    id: 101,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],
      propertyType: "Hotel",
      description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      features: {
        parking: true,
      restaurant: true,
    },
     },
     {
    id: 102,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],
     },
       {
    id: 103,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 4499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: false,
      restaurant: true,
    },
     },
    {
    id: 104,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 3499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ]
    ,   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
     {
    id: 105,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 1499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: false,
      restaurant: false,
    },
     },

    ],
  
  },

//  tomar hotel
  {
    id:10,
    name: "Hotel Siam International ",
    price: 1800,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "17A, Block 7, Block 8A, WEA, Karol Bagh, New Delhi, Delhi, 110005, India",
    image: "/hotelTomer/room/all-room/room2.webp",
    roomProperty:[
     {
    id: 10101,
    name: "Classic Room - Hotel Siam International",
    price: 1800,
    rating:[5,4,1,2,3.5,4.5,4],
    image:[
         "/hotelTomer/room/classic/classic1.jpg",
         "/hotelTomer/room/classic/classic2.jpg",
      
         "/hotelTomer/room/classic/classic3.jpg",

         "/hotelTomer/room/classic/classic-washroom.jpg",
         
    ],
      propertyType: "Hotel",
      roomAmenities:[" Wi-fi"," Parking","AC","Break-fast",],
      roomMap:"https://maps.google.com/maps?q=TOMAR+HOSPITALITY++17A%2C+Block+7%2C+Block+8A%2C+WEA%2C+Karol+Bagh%2C+New+Delhi%2C+Delhi%2C+110005%2C+India&t=&z=13&ie=UTF8&iwloc=&output=embed",
      roomLocation:"17A, Block 7, Block 8A, WEA, Karol Bagh, New Delhi, Delhi, 110005, India",
      facilities:"Rooms feature air-conditioning, private bathrooms, bathrobes, and city views. Additional amenities include free WiFi, flat-screen TVs, and work desks.",
      description:"Our Classic Room offers a cozy and inviting stay, ideal for solo travelers or couples seeking comfort and convenience in Karol Bagh, New Delhi. Designed with simplicity and functionality in mind, this room features all essential amenities to make your stay hassle-free.",
      features: {
        parking: true,
      restaurant: true,
    },
     },
     {
    id: 10102,
    name: "Deluxe Room - Hotel Siam International",
    price: 1900,
    roomAmenities:[" Wi-fi"," Parking","AC","Break-fast",],
    rating:[5,4,1,2,3.5,4.5,4],
    description:"Our Deluxe Room at Tomar Hospitality offers the perfect blend of style, space, and comfort. Ideal for both business and leisure travelers, this room is thoughtfully designed with elegant interiors and modern amenities to enhance your stay.",
    facilities:" Rooms feature air-conditioning, private bathrooms, bathrobes, and city views. Additional amenities include free WiFi, flat-screen TVs, and work desks.",
    roomMap:"https://maps.google.com/maps?q=TOMAR+HOSPITALITY++17A%2C+Block+7%2C+Block+8A%2C+WEA%2C+Karol+Bagh%2C+New+Delhi%2C+Delhi%2C+110005%2C+India&t=&z=13&ie=UTF8&iwloc=&output=embed",
    roomLocation:"17A, Block 7, Block 8A, WEA, Karol Bagh, New Delhi, Delhi, 110005, India",
    image:[
         "/hotelTomer/room/deluxe/deluxe1.jpg",
         "/hotelTomer/room/deluxe/deluxe2.jpg",
         "/hotelTomer/room/deluxe/deluxe3.jpg",
         "/hotelTomer/room/deluxe/deluxe4.jpg",
         "/hotelTomer/room/deluxe/deluxe-washroom.jpg",
      
    ],
     },
       {
    id: 103,
    name: "Super Deluxe Room - Hotel Siam International",
    price: 4499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: false,
      restaurant: true,
    },
     },
    {
    id: 104,
    name: " Family Suite Room - Hotel Siam International",
    price: 3499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ]
    ,   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
     {
    id: 105,
    name: "  Suite Room - Hotel Siam International",
    price: 1499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: false,
      restaurant: false,
    },
     },

    ],
  
  },


  {
    id: 2,
    name: "Hotel Delhi Airport",
    price: 5499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel1.jpg",
    roomProperty:[
     {
    id: 201,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 2499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ], propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
     {
    id: 202,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Apartment",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
       {
    id: 203,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 1499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Apartment",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 204,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 7499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Villa",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 205,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 5499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Villa",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },

    ],
  
  },
   {
    id: 3,
    name: "Hotel TSSG",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel2.jpg",
    roomProperty:[
     {
    id: 301,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 2499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Villa",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
     {
    id: 302,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 3499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 303,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 1499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Apartment",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: false,
    },
     },
    {
    id: 304,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 9499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 305,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 4,
    name: "Hotel PortView",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel3.jpg",
    roomProperty:[
     {
    id: 401,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 402,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 403,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 404,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 405,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 5,
    name: "Hotel YashoBhoomi",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel4.jpg",
    roomProperty:[
     {
    id: 501,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 502,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 503,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 504,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 505,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 6,
    name: "Hotel Hotel Siam International",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel5.jpg",
    roomProperty:[
     {
    id: 601,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 602,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 603,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 604,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 605,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 7,
    name: "Luxury Stay In Karol Bagh",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel6.jpg",
    roomProperty:[
     {
    id: 701,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 702,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 703,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 704,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 705,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 8,
    name: "Stay Budget Inn",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel7.jpg",
    roomProperty:[
     {
    id: 801,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 802,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 803,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 804,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 805,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
  {
    id: 9,
    name: "Hotel O Delhi",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image: "/hotel/hotel8.jpg",
    roomProperty:[
     {
    id: 901,
    name: "Classic Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room1.jpg",
         "/room/room2.jpg",
         "/room/room3.jpg",
         "/room/room4.jpg",
         "/room/room5.jpg",
         "/room/room6.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 902,
    name: "Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room7.jpg",
         "/room/room8.jpg",
         "/room/room9.jpg",
         "/room/room10.jpg",
         "/room/room11.jpg",
         "/room/room12.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
       {
    id: 903,
    name: "Super Deluxe Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room13.jpg",
         "/room/room14.jpg",
         "/room/room15.jpg",
         "/room/room16.jpg",
         "/room/room17.jpg",
         "/room/room18.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
    {
    id: 904,
    name: " Family Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room19.jpg",
         "/room/room20.jpg",
         "/room/room21.jpg",
         "/room/room22.jpg",
         "/room/room23.jpg",
         "/room/room24.jpg",
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },
     {
    id: 905,
    name: "  Suite Room - V Hotel The Grand Shoba",
    price: 6499,
    rating:[5,4,1,2,3.5,4.5,4],
    location: "Mahipalpur, Near IGI New Delhi",
    image:[
         "/room/room25.jpg",
         "/room/room26.jpg",
         "/room/room27.jpg",
         "/room/room28.jpg",
         
    ],   propertyType: "Hotel",
    description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    features: {
      parking: true,
      restaurant: true,
    },
     },

    ],
  
  },
 
];

export default data;